baseURL = "/"
languageCode = "en"
title = "ai-research.id"
author = "ai-research.id"
description = "We are a team of Machine Learning enthusiasts who love to experiment with the latest state-of-the-art Technology and publish the result as an Open Source Product."
copyright = "ai-research.id 2021"
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
# see more styles https://help.farbox.com/pygments.html
pygmentsStyle = "friendly"
footnoteReturnLinkContents = "&#8617;" # ↩
# set deliberately low for testing choose your preffered number based on the blog layout you've chosen
paginate = 3
preserveTaxonomyNames = true

[params]
  orgName = "ai-research.id"
  orgLocal = "Indonesia"
  favicon = "/img/favicon.ico?v=0"
  logo = ""
  # font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"
  # basic color options: use only color names as shown in the
  # "Color Palette" section of http://tachyons.io/docs/themes/skins/
  siteBgColor = "near-white"
  sidebarBgColor = "light-gray"
  headlineColor = "dark-pink"
  headingColor = "near-black"
  textColor = "dark-gray"
  sidebarTextColor = "mid-gray"
  bodyLinkColor = "blue"
  navLinkColor = "near-black"
  sidebarLinkColor = "near-black"
  footerTextColor = "silver"
  buttonTextColor = "near-white"
  buttonBgColor = "black"
  buttonHoverTextColor = "white"
  buttonHoverBgColor = "blue"
  borderColor = "moon-gray"
  # show/hide social icons in site header/footer
  socialInHeader = false
  socialInFooter = false

[social]
  # social accounts (username only)
  facebook = ""
  facebook_admin = "" # Facebook Page Admin ID for Domain Insights
  instagram = ""
  youtube = ""
  twitter = ""
  github = "indonesian-nlp"
  medium = ""

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
